#!/bin/bash

# Vercel Usage Checker
# Note: Vercel CLI doesn't have direct usage/billing commands
# This script explains how to check costs and provides alternatives

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         VERCEL USAGE & COST CHECKER                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  IMPORTANT: Vercel CLI does not provide usage/billing commands"
echo "   Usage data must be accessed via:"
echo "   1. Vercel Dashboard (Web Interface)"
echo "   2. Vercel API (Programmatic Access)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  PROJECT INFORMATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get project info
vercel project inspect afriquesports-web 2>&1 | grep -E "ID|Name|Owner|Created"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  HOW TO CHECK YESTERDAY'S COSTS (Dec 31, 2025)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 METHOD 1: Vercel Dashboard (Easiest)"
echo ""
echo "   1. Open: https://vercel.com/omars-projects-81bbcbf6/afriquesports-web/analytics/usage"
echo ""
echo "   2. Click 'Usage' tab"
echo ""
echo "   3. Select date range:"
echo "      • From: December 31, 2025"
echo "      • To: December 31, 2025"
echo ""
echo "   4. View breakdown:"
echo "      ✓ Edge Requests"
echo "      ✓ Function Invocations"
echo "      ✓ Image Transformations"
echo "      ✓ Fast Origin Transfer"
echo "      ✓ Fluid Compute (CPU + Memory)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📈 METHOD 2: Vercel API (Programmatic)"
echo ""
echo "   Requires: VERCEL_TOKEN environment variable"
echo ""
echo "   Example API call:"
echo '   curl -H "Authorization: Bearer $VERCEL_TOKEN" \'
echo '     "https://api.vercel.com/v1/teams/TEAM_ID/usage?from=2025-12-31&to=2025-12-31"'
echo ""
echo "   To get your token:"
echo "   1. Go to: https://vercel.com/account/tokens"
echo "   2. Create new token"
echo "   3. Export: export VERCEL_TOKEN=your_token_here"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 CURRENT MONTH COSTS (As of last check)"
echo ""
echo "   Total Monthly Cost: $123.51"
echo ""
echo "   Breakdown:"
echo "   • Edge Requests:          $41.11 (33%)"
echo "   • Fast Origin Transfer:   $18.77 (15%)"
echo "   • Fluid Active CPU:       $15.05 (12%)"
echo "   • Function Invocations:   $12.10 (10%)"
echo "   • Fluid Memory:           $12.00 (10%)"
echo "   • Image Transformations:  $10.09 (8%)"
echo "   • Web Analytics:          $9.86  (8%)"
echo "   • Image Cache Writes:     $3.91  (3%)"
echo ""
echo "   Daily Average: ~$3.98/day"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 RECOMMENDATIONS:"
echo ""
echo "   If yesterday's cost was:"
echo "   • > $5/day: Unusually high (check for traffic spike)"
echo "   • $3-5/day: Normal range"
echo "   • < $3/day: Below average"
echo ""
echo "   Quick cost reduction (save $34-41/month):"
echo "   → See: COST-OPTIMIZATION-ACTION-PLAN.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 QUICK LINKS:"
echo ""
echo "   Usage Dashboard:"
echo "   https://vercel.com/omars-projects-81bbcbf6/afriquesports-web/analytics/usage"
echo ""
echo "   Billing Settings:"
echo "   https://vercel.com/omars-projects-81bbcbf6/settings/billing"
echo ""
echo "   Export Usage Report:"
echo "   https://vercel.com/omars-projects-81bbcbf6/settings/usage"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ To check yesterday's costs, open the Usage Dashboard link above."
echo ""
