#!/bin/bash

###############################################################################
# Quick Test: Post AI Commentary for Nigeria vs Tanzania (Match 732138)
# Generated by Llama 3.1 70B on RunPod
###############################################################################

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

MATCH_ID="732138"
SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}"

echo -e "${BLUE}🎙️  Posting AI Commentary for Match ${MATCH_ID}${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# Check if webhook secret is set
if [ -z "$AI_AGENT_WEBHOOK_SECRET" ]; then
    echo -e "${RED}❌ Error: AI_AGENT_WEBHOOK_SECRET environment variable not set!${NC}"
    echo -e "${YELLOW}💡 Set it with: export AI_AGENT_WEBHOOK_SECRET='your_secret_here'${NC}\n"
    exit 1
fi

echo -e "${GREEN}✅ Webhook secret found${NC}"
echo -e "${GREEN}✅ Target: ${SITE_URL}${NC}\n"

# Function to post a single commentary event
post_event() {
    local EVENT_ID=$1
    local TIME=$2
    local TIME_SEC=$3
    local TEXT=$4
    local TYPE=$5
    local ICON=$6
    local IS_SCORING=$7

    echo -e "${BLUE}📝 Posting: ${TIME} - ${TEXT:0:60}...${NC}"

    RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
        -X POST "${SITE_URL}/api/can2025/live-commentary" \
        -H "Content-Type: application/json" \
        -H "x-webhook-secret: ${AI_AGENT_WEBHOOK_SECRET}" \
        -d @- <<EOF
{
  "match_id": "${MATCH_ID}",
  "event_id": "${EVENT_ID}",
  "time": "${TIME}",
  "time_seconds": ${TIME_SEC},
  "locale": "fr",
  "text": "${TEXT}",
  "type": "${TYPE}",
  "icon": "${ICON}",
  "is_scoring": ${IS_SCORING},
  "confidence": 0.95
}
EOF
)

    HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
    BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')

    if [ "$HTTP_STATUS" = "200" ] || [ "$HTTP_STATUS" = "201" ]; then
        echo -e "${GREEN}   ✅ Success${NC}\n"
    elif [ "$HTTP_STATUS" = "409" ]; then
        echo -e "${YELLOW}   ⚠️  Already exists (skipping)${NC}\n"
    else
        echo -e "${RED}   ❌ Failed (HTTP ${HTTP_STATUS})${NC}"
        echo -e "${RED}   ${BODY}${NC}\n"
    fi

    sleep 0.2  # Small delay between requests
}

# Post all commentary events
echo -e "${BLUE}📊 Posting 15 commentary events...${NC}\n"

post_event "${MATCH_ID}_start" "1'" 60 \
    "Le coup d'envoi est donné à Fès ! Nigeria affronte la Tanzanie dans ce match de la CAN 2025. Les Super Eagles, favoris, cherchent à confirmer leur statut après leur victoire 4-1 contre le Gabon." \
    "matchStart" "⚽" false

post_event "${MATCH_ID}_tactical_1" "12'" 720 \
    "Le Nigeria prend rapidement le contrôle du ballon avec 59% de possession. Leur capacité à trouver des espaces dans le camp adverse est impressionnante. Les Tanzaniens adoptent une approche défensive prudente." \
    "general" "📊" false

post_event "${MATCH_ID}_save_1" "23'" 1380 \
    "Belle parade du gardien tanzanien ! Le Nigeria multiplie les occasions avec déjà 6 tirs cadrés. La défense tanzanienne tient bon grâce à un gardien en grande forme." \
    "save" "🧤" false

post_event "${MATCH_ID}_corner_1" "31'" 1860 \
    "Corner pour le Nigeria ! Les Super Eagles exercent une pression constante sur la défense tanzanienne. Leur précision technique avec 89,6% de passes réussies fait la différence." \
    "corner" "🚩" false

post_event "${MATCH_ID}_ht" "45'" 2700 \
    "Mi-temps à Fès. Nigeria 0-0 Tanzanie. Match équilibré malgré la domination nigériane. Les Tanzaniens résistent héroïquement avec 7 arrêts de leur gardien." \
    "halfTime" "⏸️" false

post_event "${MATCH_ID}_2h" "46'" 2760 \
    "Reprise de la deuxième période ! Les deux équipes reviennent inchangées. Le Nigeria doit trouver la faille face à ce mur tanzanien." \
    "general" "▶️" false

post_event "${MATCH_ID}_goal_osimhen" "54'" 3240 \
    "BUUUUUT ! OSIMHEN OUVRE LE SCORE POUR LE NIGERIA ! Le chef de file de l'attaque nigériane reçoit le ballon dans la surface, élimine son défenseur et frappe du pied droit. Le ballon file dans la lucarne opposée ! 1-0 pour les Super Eagles ! Le stade explose !" \
    "goal" "⚽" true

post_event "${MATCH_ID}_chance_tz" "61'" 3660 \
    "Occasion manquée pour la Tanzanie ! Les Taifa Stars ont eu la possibilité d'égaliser mais la frappe passe juste à côté. Les supporters tanzaniens vont regretter cette occasion." \
    "missedChance" "😮" false

post_event "${MATCH_ID}_yellow" "64'" 3840 \
    "Carton jaune pour le Nigeria ! Une faute tactique pour stopper la contre-attaque tanzanienne. Les Nigérians doivent maintenir leur discipline défensive." \
    "yellowCard" "🟨" false

post_event "${MATCH_ID}_sub_etebo" "67'" 4020 \
    "Changement pour le Nigeria ! Alex Iwobi sort, Etebo entre en jeu. Le sélectionneur nigérian cherche à consolider l'avance." \
    "substitution" "🔄" false

post_event "${MATCH_ID}_goal_etebo" "69'" 4140 \
    "BUUUUUT ! ETEBO INSCRIT UN DOUBLÉ POUR LE NIGERIA ! Deux minutes après son entrée en jeu, une frappe splendide du milieu de terrain ! Le ballon vient se loger dans la lucarne ! 2-0 pour les Super Eagles ! Quel impact immédiat !" \
    "goal" "⚽" true

post_event "${MATCH_ID}_tactical_2" "72'" 4320 \
    "Après ce deuxième but, le Nigeria gère son avance. Les attaques ne sont plus aussi fréquentes et vigoureuses. La Tanzanie doit se montrer plus offensive si elle veut revenir dans le match." \
    "general" "⚡" false

post_event "${MATCH_ID}_goal_mwantika" "74'" 4440 \
    "BUT POUR LA TANZANIE ! MWANTIKA RÉDUIT LE SCORE ! Le défenseur tanzanien surgit sur corner et trompe le gardien nigérian d'une belle tête ! 2-1 ! Le but de l'honneur ravive l'espoir des Taifa Stars !" \
    "goal" "⚽" true

post_event "${MATCH_ID}_min76" "76'" 4560 \
    "À 15 minutes de la fin du match, les Nigérians semblent prêts à consolider leur avance. Avec leur domination continue, ils contrôlent les dernières minutes. La Tanzanie se mobilise pour tenter une remontée spectaculaire." \
    "general" "⏱️" false

post_event "${MATCH_ID}_stats" "78'" 4680 \
    "Les statistiques parlent d'elles-mêmes : Nigeria avec 59,3% de possession, 18 tirs dont 10 cadrés, et 89,6% de passes réussies. La Tanzanie résiste avec courage grâce à son gardien auteur de 7 arrêts." \
    "general" "📊" false

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Commentary posting complete!${NC}\n"
echo -e "${BLUE}🌐 View match at:${NC}"
echo -e "   ${SITE_URL}/can-2025/match/${MATCH_ID}\n"
echo -e "${YELLOW}💡 Tip: Wait 15 seconds for Next.js ISR to revalidate, then refresh the page${NC}\n"
