import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * GET /api/can2025/match-formations
 * Returns team formations generated by the autonomous agent
 *
 * Query params:
 * - match_id: The match ID (e.g., "test-brazil-france-2006")
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const matchId = searchParams.get('match_id');

    if (!matchId) {
      return NextResponse.json(
        { error: 'match_id is required' },
        { status: 400 }
      );
    }

    // Fetch formations from prematch_analysis table (generated by autonomous agent)
    const { data, error } = await supabase
      .from('match_prematch_analysis')
      .select('match_id, home_formation, away_formation, home_lineup, away_lineup, home_coach, away_coach')
      .eq('match_id', matchId)
      .eq('locale', 'fr') // Match the locale used when saving formations
      .single();

    if (error) {
      console.error('Error fetching formations:', error);
      return NextResponse.json(
        { formations: null },
        { status: 200 }
      );
    }

    // Transform to match UI expectations
    const formations = {
      home_team: {
        formation: data.home_formation,
        lineup: {
          starters: data.home_lineup || [],
          coach: data.home_coach
        }
      },
      away_team: {
        formation: data.away_formation,
        lineup: {
          starters: data.away_lineup || [],
          coach: data.away_coach
        }
      }
    };

    return NextResponse.json({ formations });
  } catch (error: any) {
    console.error('Error in match-formations API:', error);
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 }
    );
  }
}

/**
 * POST /api/can2025/match-formations
 * Allows the autonomous agent to save formations
 *
 * Expected body:
 * {
 *   "match_id": "test-brazil-france-2006",
 *   "home_formation": "4-4-2",
 *   "away_formation": "4-5-1",
 *   "home_lineup": [{position: "GK", name: "Dida", number: "1"}, ...],
 *   "away_lineup": [{position: "GK", name: "Barthez", number: "16"}, ...],
 *   "home_coach": "Carlos Alberto Parreira",
 *   "away_coach": "Raymond Domenech"
 * }
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { match_id, home_formation, away_formation, home_lineup, away_lineup, home_coach, away_coach } = body;

    if (!match_id || !home_formation || !away_formation) {
      return NextResponse.json(
        { error: 'match_id, home_formation, and away_formation are required' },
        { status: 400 }
      );
    }

    // Upsert formations to prematch_analysis table
    const { data, error } = await supabase
      .from('match_prematch_analysis')
      .upsert({
        match_id,
        locale: 'fr', // Default locale for autonomous agent formations
        home_formation,
        away_formation,
        home_lineup: home_lineup || [],
        away_lineup: away_lineup || [],
        home_coach: home_coach || null,
        away_coach: away_coach || null,
        updated_at: new Date().toISOString()
      }, {
        onConflict: 'match_id,locale'
      })
      .select()
      .single();

    if (error) {
      console.error('Error saving formations:', error);
      return NextResponse.json(
        { error: 'Failed to save formations', message: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      formations: data
    });
  } catch (error: any) {
    console.error('Error in match-formations POST:', error);
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 }
    );
  }
}
